import { jsPDF } from "jspdf";
import type {
  AnalysisResult,
  RiskItem,
  KeyDate,
  FinancialObligation,
  MissingClause,
  ActionItem,
} from "@/types";

// ── Colors ──────────────────────────────────────────────────────────────────
const COLOR = {
  primary: [0, 21, 79] as const, // #00154f
  error: [186, 26, 26] as const, // #ba1a1a
  warning: [124, 88, 0] as const, // #7c5800
  success: [0, 109, 59] as const, // #006d3b
  dark: [28, 27, 31] as const, // #1c1b1f
  muted: [73, 69, 79] as const, // #49454f
  lightBg: [245, 245, 245] as const, // #f5f5f5
  white: [255, 255, 255] as const,
};

// ── Layout constants ────────────────────────────────────────────────────────
const MARGIN = 20;
const PAGE_W = 210;
const PAGE_H = 297;
const CONTENT_W = PAGE_W - MARGIN * 2;
const SAFE_BOTTOM = 277; // leave room for footer

type RGB = readonly [number, number, number];

// ── Helpers ─────────────────────────────────────────────────────────────────

function setColor(doc: jsPDF, c: RGB) {
  doc.setTextColor(c[0], c[1], c[2]);
}

function setFillColor(doc: jsPDF, c: RGB) {
  doc.setFillColor(c[0], c[1], c[2]);
}

/** Check if we need a page break. If so, add a page and return the new Y. */
function ensureSpace(doc: jsPDF, y: number, needed: number): number {
  if (y + needed > SAFE_BOTTOM) {
    doc.addPage();
    return MARGIN + 5;
  }
  return y;
}

/** Draw a section header with a line underneath. Returns new Y. */
function sectionHeader(doc: jsPDF, title: string, y: number): number {
  y = ensureSpace(doc, y, 20);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  setColor(doc, COLOR.primary);
  doc.text(title, MARGIN, y);
  y += 2;
  doc.setDrawColor(COLOR.primary[0], COLOR.primary[1], COLOR.primary[2]);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;
  return y;
}

/** Draw wrapped body text. Returns new Y. */
function bodyText(doc: jsPDF, text: string, y: number, maxW?: number): number {
  const w = maxW ?? CONTENT_W;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  setColor(doc, COLOR.dark);
  const lines: string[] = doc.splitTextToSize(text, w);
  for (const line of lines) {
    y = ensureSpace(doc, y, 5);
    doc.text(line, MARGIN, y);
    y += 5;
  }
  return y;
}

/** Small label text. Returns new Y. */
function labelText(
  doc: jsPDF,
  label: string,
  value: string,
  y: number
): number {
  y = ensureSpace(doc, y, 6);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  setColor(doc, COLOR.muted);
  doc.text(label, MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  setColor(doc, COLOR.dark);
  doc.text(value, MARGIN + 35, y);
  y += 6;
  return y;
}

function severityColor(severity: string): RGB {
  if (severity === "high") return COLOR.error;
  if (severity === "medium") return COLOR.warning;
  return COLOR.success;
}

function severityLabel(severity: string): string {
  if (severity === "high") return "HIGH";
  if (severity === "medium") return "MEDIUM";
  return "LOW";
}

function priorityLabel(p: string): string {
  return p.charAt(0).toUpperCase() + p.slice(1);
}

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  } catch {
    return iso;
  }
}

// ── Footer ──────────────────────────────────────────────────────────────────

function drawFooter(doc: jsPDF, dateStr: string) {
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const footerY = PAGE_H - 10;

    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, footerY - 4, PAGE_W - MARGIN, footerY - 4);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    setColor(doc, COLOR.muted);

    doc.text(`Page ${i} of ${totalPages}`, MARGIN, footerY);
    doc.text(
      `Generated by The Curator \u00B7 ${dateStr}`,
      PAGE_W / 2,
      footerY,
      { align: "center" }
    );
    doc.text(
      "For informational purposes only \u2014 not legal advice.",
      PAGE_W - MARGIN,
      footerY,
      { align: "right" }
    );
  }
}

// ── Main generator ──────────────────────────────────────────────────────────

export async function generateContractPDF(contract: {
  title: string;
  type: string;
  created_at: string;
  risk_score: number;
  risk_high: boolean;
  result: AnalysisResult;
}): Promise<Buffer> {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const result = contract.result;
  const dateStr = formatDate(contract.created_at);

  // ═══════════════════════════════════════════════════════════════════════════
  // PAGE 1: COVER / SUMMARY
  // ═══════════════════════════════════════════════════════════════════════════

  let y = MARGIN;

  // Brand header bar
  setFillColor(doc, COLOR.primary);
  doc.rect(0, 0, PAGE_W, 40, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  setColor(doc, COLOR.white);
  doc.text("The Curator", MARGIN, 18);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text("Contract Analysis Report", MARGIN, 28);

  y = 55;

  // Contract title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  setColor(doc, COLOR.dark);
  const titleLines: string[] = doc.splitTextToSize(
    contract.title || "Untitled Contract",
    CONTENT_W
  );
  for (const line of titleLines) {
    doc.text(line, MARGIN, y);
    y += 9;
  }
  y += 2;

  // Contract type badge
  if (contract.type || result.contractType) {
    const typeText = contract.type || result.contractType || "";
    doc.setFontSize(9);
    const badgeW = doc.getTextWidth(typeText) + 8;
    setFillColor(doc, COLOR.lightBg);
    doc.roundedRect(MARGIN, y - 4, badgeW, 7, 2, 2, "F");
    doc.setFont("helvetica", "bold");
    setColor(doc, COLOR.primary);
    doc.text(typeText, MARGIN + 4, y);
    y += 12;
  }

  // Date
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  setColor(doc, COLOR.muted);
  doc.text(`Analyzed on ${dateStr}`, MARGIN, y);
  y += 14;

  // ── Score cards row ─────────────────────────────────────────────────────
  const cardW = (CONTENT_W - 10) / 2;
  const cardH = 40;
  const cardX1 = MARGIN;
  const cardX2 = MARGIN + cardW + 10;

  // Risk score card
  setFillColor(doc, COLOR.lightBg);
  doc.roundedRect(cardX1, y, cardW, cardH, 3, 3, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  setColor(doc, COLOR.muted);
  doc.text("RISK SCORE", cardX1 + cardW / 2, y + 8, { align: "center" });

  const riskScore = contract.risk_score ?? result.riskScore ?? 0;
  const riskColor = riskScore >= 70 ? COLOR.error : riskScore >= 40 ? COLOR.warning : COLOR.success;

  doc.setFontSize(28);
  setColor(doc, riskColor);
  doc.text(`${riskScore}`, cardX1 + cardW / 2, y + 24, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const riskLabel =
    riskScore >= 70 ? "High Risk" : riskScore >= 40 ? "Medium Risk" : "Low Risk";
  doc.text(riskLabel, cardX1 + cardW / 2, y + 32, { align: "center" });

  // Fairness score card
  setFillColor(doc, COLOR.lightBg);
  doc.roundedRect(cardX2, y, cardW, cardH, 3, 3, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  setColor(doc, COLOR.muted);
  doc.text("FAIRNESS SCORE", cardX2 + cardW / 2, y + 8, { align: "center" });

  const fairness = result.fairnessScore ?? 50;
  const fairnessColor =
    fairness >= 40 && fairness <= 60
      ? COLOR.success
      : fairness >= 25 && fairness <= 75
        ? COLOR.warning
        : COLOR.error;

  doc.setFontSize(28);
  setColor(doc, fairnessColor);
  doc.text(`${fairness}`, cardX2 + cardW / 2, y + 24, { align: "center" });

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  const fairLabel =
    fairness >= 40 && fairness <= 60
      ? "Balanced"
      : fairness < 40
        ? "Favors Party A"
        : "Favors Party B";
  doc.text(fairLabel, cardX2 + cardW / 2, y + 32, { align: "center" });

  y += cardH + 14;

  // Executive summary
  y = sectionHeader(doc, "Executive Summary", y);
  if (result.summary) {
    y = bodyText(doc, result.summary, y);
  }

  // Fairness summary (if available)
  if (result.fairnessSummary) {
    y += 4;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    setColor(doc, COLOR.muted);
    const fLines: string[] = doc.splitTextToSize(result.fairnessSummary, CONTENT_W);
    for (const line of fLines) {
      y = ensureSpace(doc, y, 5);
      doc.text(line, MARGIN, y);
      y += 4.5;
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // RISK ANALYSIS
  // ═══════════════════════════════════════════════════════════════════════════

  const risks = result.risks ?? [];
  if (risks.length > 0) {
    doc.addPage();
    y = MARGIN + 5;

    y = sectionHeader(
      doc,
      `Risk Analysis (${risks.length} risk${risks.length > 1 ? "s" : ""})`,
      y
    );

    for (let i = 0; i < risks.length; i++) {
      const risk: RiskItem = risks[i];
      y = ensureSpace(doc, y, 35);

      // Severity badge
      const sColor = severityColor(risk.severity);
      const sLabel = severityLabel(risk.severity);
      const badgeW = doc.setFontSize(8).getTextWidth(sLabel) + 6;
      setFillColor(doc, sColor);
      doc.roundedRect(MARGIN, y - 3.5, badgeW, 5.5, 1.5, 1.5, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      setColor(doc, COLOR.white);
      doc.text(sLabel, MARGIN + 3, y);

      // Risk title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(11);
      setColor(doc, COLOR.dark);
      doc.text(risk.title, MARGIN + badgeW + 4, y);
      y += 7;

      // Clause (quoted, gray background)
      if (risk.clause) {
        const clauseLines: string[] = doc.splitTextToSize(
          `"${risk.clause}"`,
          CONTENT_W - 8
        );
        const clauseH = clauseLines.length * 4.5 + 4;
        y = ensureSpace(doc, y, clauseH + 2);
        setFillColor(doc, COLOR.lightBg);
        doc.roundedRect(MARGIN, y - 3, CONTENT_W, clauseH, 1.5, 1.5, "F");
        doc.setFont("helvetica", "italic");
        doc.setFontSize(9);
        setColor(doc, COLOR.muted);
        for (const line of clauseLines) {
          doc.text(line, MARGIN + 4, y);
          y += 4.5;
        }
        y += 2;
      }

      // Explanation
      if (risk.explanation) {
        y = ensureSpace(doc, y, 10);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        setColor(doc, COLOR.dark);
        const expLines: string[] = doc.splitTextToSize(risk.explanation, CONTENT_W);
        for (const line of expLines) {
          y = ensureSpace(doc, y, 4.5);
          doc.text(line, MARGIN, y);
          y += 4.5;
        }
        y += 2;
      }

      // Suggestion
      if (risk.suggestion) {
        y = ensureSpace(doc, y, 10);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        setColor(doc, COLOR.success);
        doc.text("Suggestion:", MARGIN, y);
        y += 4.5;
        doc.setFont("helvetica", "normal");
        setColor(doc, COLOR.dark);
        const sugLines: string[] = doc.splitTextToSize(risk.suggestion, CONTENT_W);
        for (const line of sugLines) {
          y = ensureSpace(doc, y, 4.5);
          doc.text(line, MARGIN, y);
          y += 4.5;
        }
        y += 2;
      }

      // Suggested Rewrite
      if (risk.rewrite) {
        y = ensureSpace(doc, y, 10);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        setColor(doc, COLOR.primary);
        doc.text("Suggested Rewrite:", MARGIN, y);
        y += 4.5;
        const rwLines: string[] = doc.splitTextToSize(risk.rewrite, CONTENT_W - 8);
        const rwH = rwLines.length * 4.5 + 4;
        y = ensureSpace(doc, y, rwH);
        setFillColor(doc, COLOR.lightBg);
        doc.roundedRect(MARGIN, y - 3, CONTENT_W, rwH, 1.5, 1.5, "F");
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        setColor(doc, COLOR.dark);
        for (const line of rwLines) {
          doc.text(line, MARGIN + 4, y);
          y += 4.5;
        }
        y += 4;
      }

      // Divider between risks
      if (i < risks.length - 1) {
        y = ensureSpace(doc, y, 6);
        doc.setDrawColor(220, 220, 220);
        doc.setLineWidth(0.2);
        doc.line(MARGIN, y, PAGE_W - MARGIN, y);
        y += 6;
      }
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // KEY DATES & FINANCIAL OBLIGATIONS
  // ═══════════════════════════════════════════════════════════════════════════

  const keyDates = result.keyDates ?? [];
  const financials = result.financialObligations ?? [];

  if (keyDates.length > 0 || financials.length > 0) {
    doc.addPage();
    y = MARGIN + 5;

    // Key Dates table
    if (keyDates.length > 0) {
      y = sectionHeader(doc, "Key Dates", y);

      // Table header
      const col1 = MARGIN;
      const col2 = MARGIN + 60;
      const col3 = MARGIN + 120;

      setFillColor(doc, COLOR.primary);
      doc.roundedRect(MARGIN, y - 4, CONTENT_W, 7, 1, 1, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      setColor(doc, COLOR.white);
      doc.text("LABEL", col1 + 3, y);
      doc.text("DATE", col2 + 3, y);
      doc.text("IMPORTANCE", col3 + 3, y);
      y += 6;

      for (const kd of keyDates) {
        y = ensureSpace(doc, y, 7);
        const rowColor: RGB =
          kd.importance === "critical" ? COLOR.error : COLOR.muted;

        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        setColor(doc, COLOR.dark);
        doc.text(kd.label, col1 + 3, y);
        doc.text(kd.date, col2 + 3, y);

        setColor(doc, rowColor);
        doc.setFont("helvetica", "bold");
        doc.text(
          kd.importance === "critical" ? "Critical" : "Notable",
          col3 + 3,
          y
        );
        y += 6;

        doc.setDrawColor(230, 230, 230);
        doc.setLineWidth(0.15);
        doc.line(MARGIN, y - 2, PAGE_W - MARGIN, y - 2);
      }
      y += 8;
    }

    // Financial Obligations table
    if (financials.length > 0) {
      y = sectionHeader(doc, "Financial Obligations", y);

      const fCol1 = MARGIN;
      const fCol2 = MARGIN + 55;
      const fCol3 = MARGIN + 95;
      const fCol4 = MARGIN + 125;

      setFillColor(doc, COLOR.primary);
      doc.roundedRect(MARGIN, y - 4, CONTENT_W, 7, 1, 1, "F");
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      setColor(doc, COLOR.white);
      doc.text("DESCRIPTION", fCol1 + 3, y);
      doc.text("AMOUNT", fCol2 + 3, y);
      doc.text("PARTY", fCol3 + 3, y);
      doc.text("CONDITION", fCol4 + 3, y);
      y += 6;

      for (const fo of financials) {
        y = ensureSpace(doc, y, 12);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        setColor(doc, COLOR.dark);

        // Description may wrap
        const descLines: string[] = doc.splitTextToSize(fo.description, 52);
        const amtLines: string[] = doc.splitTextToSize(fo.amount, 37);
        const condLines: string[] = doc.splitTextToSize(
          fo.condition || "-",
          CONTENT_W - 125
        );

        const maxLines = Math.max(
          descLines.length,
          amtLines.length,
          condLines.length,
          1
        );
        const rowH = maxLines * 4.5;
        y = ensureSpace(doc, y, rowH + 2);

        let ty = y;
        for (const l of descLines) {
          doc.text(l, fCol1 + 3, ty);
          ty += 4.5;
        }
        ty = y;
        for (const l of amtLines) {
          doc.text(l, fCol2 + 3, ty);
          ty += 4.5;
        }
        doc.text(fo.party, fCol3 + 3, y);
        ty = y;
        for (const l of condLines) {
          doc.text(l, fCol4 + 3, ty);
          ty += 4.5;
        }

        y += rowH + 2;
        doc.setDrawColor(230, 230, 230);
        doc.setLineWidth(0.15);
        doc.line(MARGIN, y - 1, PAGE_W - MARGIN, y - 1);
      }
      y += 6;
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // MISSING CLAUSES & ACTION ITEMS
  // ═══════════════════════════════════════════════════════════════════════════

  const missing = result.missingClauses ?? [];
  const actions = result.actionItems ?? [];

  if (missing.length > 0 || actions.length > 0) {
    doc.addPage();
    y = MARGIN + 5;

    // Missing Clauses
    if (missing.length > 0) {
      y = sectionHeader(doc, "Missing Clauses", y);

      for (const mc of missing) {
        y = ensureSpace(doc, y, 20);

        // Warning card
        const impColor: RGB =
          mc.importance === "high" ? COLOR.error : COLOR.warning;

        // Title with importance badge
        const impLabel = mc.importance === "high" ? "HIGH" : "MEDIUM";
        const impBadgeW = doc.setFontSize(7).getTextWidth(impLabel) + 5;

        setFillColor(doc, impColor);
        doc.roundedRect(MARGIN, y - 3, impBadgeW, 5, 1.5, 1.5, "F");
        doc.setFont("helvetica", "bold");
        doc.setFontSize(7);
        setColor(doc, COLOR.white);
        doc.text(impLabel, MARGIN + 2.5, y);

        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        setColor(doc, COLOR.dark);
        doc.text(mc.title, MARGIN + impBadgeW + 4, y);
        y += 6;

        // Reason
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        setColor(doc, COLOR.muted);
        const reasonLines: string[] = doc.splitTextToSize(mc.reason, CONTENT_W);
        for (const line of reasonLines) {
          y = ensureSpace(doc, y, 4.5);
          doc.text(line, MARGIN, y);
          y += 4.5;
        }
        y += 4;
      }
      y += 4;
    }

    // Action Items
    if (actions.length > 0) {
      // Sort by priority: high -> medium -> low
      const priorityOrder: Record<string, number> = {
        high: 0,
        medium: 1,
        low: 2,
      };
      const sorted = [...actions].sort(
        (a, b) =>
          (priorityOrder[a.priority] ?? 2) - (priorityOrder[b.priority] ?? 2)
      );

      y = sectionHeader(doc, "Action Items", y);

      for (const ai of sorted) {
        y = ensureSpace(doc, y, 14);

        // Priority indicator
        const pColor = severityColor(ai.priority);
        setFillColor(doc, pColor);
        doc.circle(MARGIN + 2, y - 1.2, 1.8, "F");

        // Action text
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        setColor(doc, COLOR.dark);
        const actionLines: string[] = doc.splitTextToSize(ai.action, CONTENT_W - 10);
        let ay = y;
        for (const line of actionLines) {
          ay = ensureSpace(doc, ay, 4.5);
          doc.text(line, MARGIN + 7, ay);
          ay += 4.5;
        }

        // Party + deadline + priority
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        setColor(doc, COLOR.muted);
        const meta: string[] = [];
        if (ai.party) meta.push(`Party: ${ai.party}`);
        if (ai.deadline) meta.push(`Deadline: ${ai.deadline}`);
        meta.push(`Priority: ${priorityLabel(ai.priority)}`);
        doc.text(meta.join("  |  "), MARGIN + 7, ay);
        ay += 6;

        y = ay + 2;
      }
    }
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // FOOTERS (drawn last across all pages)
  // ═══════════════════════════════════════════════════════════════════════════

  drawFooter(doc, dateStr);

  // ── Output ──────────────────────────────────────────────────────────────
  const arrayBuffer = doc.output("arraybuffer");
  return Buffer.from(arrayBuffer);
}
